services:
  database:
    image: postgres:latest
    container_name: shopi-postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=shopi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopi-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "shopi-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shopi-network

  shopi.identity.api:
    image: shopi.identity.api
    build:
      context: .
      dockerfile: Shopi.Identity.API/Dockerfile
    ports:
      - "5143:8082"
    networks:
      - shopi-network
    depends_on:
      - database

  shopi.bff:
    image: shopi.bff
    build:
      context: .
      dockerfile: Shopi.BFF/Dockerfile
    ports:
      - "5200:8080"
    networks:
      - shopi-network
    depends_on:
      - database

  shopi.customer.api:
    image: shopi.customer.api
    build:
      context: .
      dockerfile: Shopi.Customer.API/Dockerfile
    ports:
      - "5118:8081"
    networks:
      - shopi-network
    depends_on:
      - database

  shopi.admin.api:
    image: shopi.admin.api
    build:
      context: .
      dockerfile: Shopi.Admin.API/Dockerfile
    ports:
      - "5129:8083"
    networks:
      - shopi-network
    depends_on:
      - database
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shopi-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=shopi_db
    volumes:
      - mongo-data:/data/db
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      - app-network

networks:
  shopi-network:

volumes:
  postgres_data:
  mongo-data:
